[package]
name = "advent_2025"
version = "0.1.0"
edition = "2021"

[dependencies]
automod = "1.0.13"
clap = { version = "4.4.10", features = ["derive"] }
curl = "0.4.46"
inventory = "0.3.13"
rayon = "1.8.0"
regex = "1.10.2"
openssl = "^0.10"

[features]
vendored-openssl = ["openssl/vendored"]
